### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by tomthebotfly** [cyclowns/tf2-rich-presence#4]
OS: Windows 10 Pro 64-Bit
TF2 and Discord all latest version.
Cyclowns Rich Presence on pre-release v1.3.2
Already uninstalled and reinstalled successfully, both as admin.

Issue: During gameplay, the Rich Presence works well, starts with the game and transmits the right info. However, after some time, an alert pops up (see image)
![image](https://user-images.githubusercontent.com/64895167/84135454-4f1fb000-aa4a-11ea-9d7c-3f5675158c3b.png)
The app stops transmitting info to Discord and after I quit the game, Discord is still stuck with the same info
![image](https://user-images.githubusercontent.com/64895167/84135490-58a91800-aa4a-11ea-8b60-c9c29bc11cb9.png)
This picture was taken with the game closed after playing it for around 30 minutes.
This was the first version I downloaded, so I cannot confirm nor deny this was an issue in previous versions as well. It happens on both community and casual Valve servers. The only way to get rid of the Playing Team Fortress 2 status on Discord is to quit and restart the app. It seems as if something stops the app from communicating with Team Fortress 2 in the middle of the game. I did not type "retry" in the console and -condebug is in my launch options.

**Comment by tomthebotfly** [comment]
I am going to try and see if this happens on v1.3.1
I am going to edit this comment if I manage to recreate the issue.

**Comment by mirrorcult** [comment]
ive had this happen before and i think i know why, lemme try and fix it and I'll push a.new version

**Comment by mirrorcult** [comment]
thanks for issue submission btw, wasnt sure if everyone had this problem

**Comment by mirrorcult** [comment]
well i played for 4 hours and couldn't replicate it so i dont know if its fixed or not

**Comment by ghost** [comment]
Got a similar issue, it does not detect whether I am in queue or in a self hosting server, and it takes a while to realize that I have disconnected from a server.

**Comment by mirrorcult** [comment]
those are not bugs, just quirks of how it retrieves server information

**Comment by tomthebotfly** [comment]
Ok, I tried installing and building from the source code and must have broken something along the way because now it just doesn't start anymore lol.
I am going to take your word for it and close this issue. Thanks for the help :)

**Comment by mirrorcult** [comment]
@tomthebotfly , sorry, not your issue, the one @xqzba brought up. the 'failed to execute script main' is still a bug im trying to fix

**Comment by tomthebotfly** [comment]
Oh ok. I managed to get the software working and built from the source code, and I have not encountered the problem so far, so I thought you had fixed it.

**Comment by tomthebotfly** [comment]
Yeah, I can confirm the issue is still there. Another thing I noticed is that sometimes the alert comes up multiple times. Nothing else changes but it comes up multiple times, I assume at different times during gameplay.

**Comment by mirrorcult** [comment]
when i run the game through python instead of the executable it seems to work fine so that's worrying

**Comment by mirrorcult** [comment]
okay, i'm pretty sure i found out why it's happening
https://github.com/giampaolo/psutil/issues/787

unfixed issue for 4 years, so its looking like my options are to either find an alternative to psutil or an alternative to pyinstaller

**Comment by mirrorcult** [comment]
news, finally, fixed the bug by switching from pyinstaller to cxfreeze. also streamlines the build process a little bit. just need to do finishing touches and tests and i can merge it

**Comment by mirrorcult** [comment]
@tomthebotfly

**Comment by mirrorcult** [comment]
let me know if it works, if you still use this program

**Comment by tomthebotfly** [comment]
I will test it later today when I'm back at home, thanks again for the work.

**Comment by tomthebotfly** [comment]
I've tested it over the past week, it works perfectly now. Thanks again.
